# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jta < Formula
  desc "AI-powered Agentic JSON Translation tool"
  homepage "https://github.com/hikanner/jta"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hikanner/jta/releases/download/v1.0.0/jta_Darwin_x86_64.tar.gz"
      sha256 "70e521986154922c0d37528d1f9de709cc96e2ee03e155c2f444cf406f0d1d26"

      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hikanner/jta/releases/download/v1.0.0/jta_Darwin_arm64.tar.gz"
      sha256 "8e910976fe80255d74aec9958e0dfa581825b2a8e060f5943f3b640c6078191e"

      def install
        bin.install "jta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.0.0/jta_Linux_x86_64.tar.gz"
      sha256 "047efca53067e65bb90a459a85832efc93408bdd040aef53efff116922b4722f"
      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.0.0/jta_Linux_arm64.tar.gz"
      sha256 "8f6af12dd2108ef3e00dee5123b3ed46f895b4b5be94980445ee6b9bf630cfcf"
      def install
        bin.install "jta"
      end
    end
  end

  test do
    system "#{bin}/jta", "--version"
  end
end
