# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jta < Formula
  desc "AI-powered Agentic JSON Translation tool"
  homepage "https://github.com/hikanner/jta"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Darwin_x86_64.tar.gz"
      sha256 "c9c95b49cb30bcfcdc3fa4baf941a9e64a9b5785205575835caf63228d521c9e"

      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Darwin_arm64.tar.gz"
      sha256 "9defa63992f6c5bd95adc54ec0ff09ef7622f40a99b50a8c909c714926cf26b4"

      def install
        bin.install "jta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Linux_x86_64.tar.gz"
      sha256 "f9b1bb111f5ceff0c9cfc199b7ffe7e4993f27c3609ed3ba06b8cfb8207837d7"
      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Linux_arm64.tar.gz"
      sha256 "ff10f2068f09ccf4b4583e3b7d8f2d3483aed6b362e04457b43cecce791500b6"
      def install
        bin.install "jta"
      end
    end
  end

  test do
    system "#{bin}/jta", "--version"
  end
end
