# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jta < Formula
  desc "AI-powered Agentic JSON Translation tool"
  homepage "https://github.com/hikanner/jta"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Darwin_x86_64.tar.gz"
      sha256 "de42052724c9ae72cc82fbd16f6170cfaff0ab5723114cb911f39ee1cb0588fd"

      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Darwin_arm64.tar.gz"
      sha256 "12a58c48d7532eb24c0dd17283e6524c55049b7460170b5452f93dc3a75e7d53"

      def install
        bin.install "jta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Linux_x86_64.tar.gz"
      sha256 "41a0e37faac0080856fca245c1dfc1f0b867d67c8dadd26c41396cf732bc6388"
      def install
        bin.install "jta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hikanner/jta/releases/download/v1.1.0/jta_Linux_arm64.tar.gz"
      sha256 "4b9cdce62a2fd4582a9331696349428e1e10850511f27a6f64b96484e75c391c"
      def install
        bin.install "jta"
      end
    end
  end

  test do
    system "#{bin}/jta", "--version"
  end
end
